mindee/tawazi

.github/workflows/python-app.yml
pyproject.toml

Changed dependency management from flit to poetry

chg: :recycle: switched from flit to poetry

---

.github/dependabot.yml

:sparkles: create dependabot.yml file

---

.github/workflows/python-app.yml
.gitignore
.pre-commit-config.yaml
README.md
mypy.ini
pyproject.toml
tawazi/__init__.py
tawazi/config.py
tawazi/dag.py
tawazi/errors.py
tawazi/ops.py
tests/test_methods.py

- this PR also contains minor refacto

Enforce strict mypy on the code and add mypy to the CI

---

pyproject.toml
requirements.txt
scripts/validate_config_options.py
tawazi/__init__.py
tawazi/config.py
tawazi/dag.py
tawazi/node.py
tests/test_config.py
tests/test_priority_sequential.py

Changed the basic logger to loguru for more detailed information
added a proper configuration handled with pydantic

:sparkles: changed logger to loguru and added pydantic config

---

.github/workflows/python-app.yml
.pre-commit-config.yaml
README.md
tawazi/config.py
tawazi/dag.py
tests/test_priority_sequential.py
tests/test_safe_execution.py

2nd to final PR before Release

Run functions safely

---

README.md
documentation/future_developments.md
documentation/home.md
mkdocs.yml
pyproject.toml

mkdocs static documentation + readme cleaning

:sparkles: mkdocs general documentation and readme cleanse

---

tawazi/dag.py
tests/test_build.py
tests/test_graph.py

:sparkles: :white_check_mark: improved coverage

---

README.md
documentation/future_developments.md
tawazi/node.py
tawazi/ops.py
tests/test_execution_time.py

Final PR before release of Tawazi 0.2.0

Documentation

---

.github/workflows/python-app.yml
README.md
pyproject.toml

chg: :recycle: :green_heart: integrated codecov 

---

tawazi/config.py

Changed config vars in order to avoid conflicts

chg: :recycle: renaming of the env vars in the config to avoid conflicts

---

.pre-commit-config.yaml
README.md
tawazi/dag.py
tests/test_safe_execution.py

Documentation  for Users
Document:
* Parallelism
* Easy Interface (arguments passing and return values to and from pipeline)
* Setup ExecNodes
* Debug ExecNodes
* is_sequence

new: :sparkles: :memo: documentation

---

README.md
example.py
tawazi/__init__.py
tawazi/decorators.py
tawazi/node.py
tests/test_compound_priority.py
tests/test_debug_nodes.py
tests/test_decorator.py
tests/test_edge_cases_dag.py
tests/test_error_during_dag_build.py
tests/test_execution_time.py
tests/test_imbricated_dags.py
tests/test_methods.py
tests/test_multiple_return_value_for_graph.py
tests/test_op.py
tests/test_ops_interface.py
tests/test_pipeline_input_output.py
tests/test_safe_execution.py
tests/test_same_op_reuse.py
tests/test_setup_nodes.py
tests/test_subgraph.py
tests/test_tags.py
tests/test_wrapped_function.py

rename xnode -> xn
rename to_dag -> dag

Interface renaming

---

tawazi/decorators.py
tawazi/node.py
tests/test_setup_nodes.py

small edge case fix and better error msg
https://github.com/mindee/tawazi/issues/69
https://github.com/mindee/tawazi/issues/77

chg: :recycle: fix edge case, better error message

---

.bandit
pyproject.toml
tawazi/dag.py
tawazi/digraph.py
tawazi/helpers.py
tawazi/node.py
tests/test_dag_config.py

Allows for configuring the dag from a dictionary, a json and a yaml file

new: :sparkles: allow for dag config from yaml, json and dict

---

tawazi/config.py
tawazi/dag.py
tawazi/node.py
tawazi/profile.py
tests/test_debug_nodes.py
tests/test_profiling.py

[FEATURE] Profiling

---

tawazi/dag.py
tests/test_dagexecutor.py

In order to be able to exchange information between the main thread and the ExecNode's thread directly, in a threadsafe manner, and without passing the information using the arguments / return value... we can use a prefix in the name of the threads that are launched by tawazi... this thread prefix is common to all threads and can be changed as needed (for example we can change it for every invocation of the DAG instance).

[FEATURE] new: :sparkles: exchange thread_name_prefix with launched threads

---

tawazi/dag.py
tests/test_cache_feature.py

new: :sparkles: cache_deps_of a feature (run it but do not cache it)

---

README.md
pyproject.toml
tawazi/consts.py
tawazi/dag.py
tawazi/decorators.py
tawazi/digraph.py
tawazi/helpers.py
tawazi/node.py
tests/test_behavior.py
tests/test_build.py
tests/test_error_during_dag_build.py
tests/test_graph.py
tests/test_multiple_return_value_for_exec_node.py
tests/test_priority_sequential.py
tests/test_typing.py

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Multiple return values

---

tawazi/consts.py
tawazi/dag.py
tawazi/decorators.py
tawazi/node.py
tests/test_tags.py

Use multiple a single tag or multiple tags for a single ExecNode

chg: :sparkles: multiple tags

---

documentation/index.md

:memo: start to document basic operations

---

.github/workflows/testing-workflow.yml
documentation/future_developments.md
documentation/index.md
pyproject.toml

Replace mkcodes with pytest-codeblocks which is better updated

fire: ➖ replace mkcodes with pytest --codeblocks

---

documentation/dag.md
documentation/index.md
mkdocs.yml
tawazi/dag.py
tawazi/digraph.py
tests/test_dag_compose.py

Compose a SubDag from a DAG by specifying the inputs and the outputs

Composition feature

---

documentation/index.md
tawazi/node/node.py
tests/test_edge_cases_dag.py

Add support for callable without a qualname attribute
A test including bad edge cases of node declaration

chg: :recycle: add support for anonymous functions

---

documentation/index.md
tawazi/node/node.py

Add support for partial functions by forwarding the annotations and the qualname

chg: :recycle: add edge case for partial functions

---

.pre-commit-config.yaml
tests/test_config.py
tests/test_op.py
tests/test_typing.py

Update ruff and remove some useless hooks

Remove useless precommit hooks

---

documentation/index.md
documentation/others.md
mkdocs.yml
tawazi/__init__.py
tawazi/_dag/digraph.py
tawazi/_dag/helpers.py
tawazi/_decorators.py
tawazi/config.py
tawazi/consts.py
tawazi/node/node.py
tests/test_behavior.py
tests/test_config.py
tests/test_resource.py

Choose where the ExecNode runs

Resource choice feature

---

CHANGELOG.md
pyproject.toml
tawazi/__init__.py

1. change log
2. tag v0.3.0
3.

Release 0.3.0

---

.pre-commit-config.yaml
pyproject.toml
tawazi/_dag/dag.py
tawazi/config.py
tests/test_debug_nodes.py
tests/test_edge_cases_dag.py

fix issue of hanging when a debug ExecNode depends on a constant and variable

Fix issue 205

---

CHANGELOG.md
pyproject.toml
tawazi/__init__.py

chg: :bookmark: preparing v0.3.1

---

README.md
documentation/index.md
pyproject.toml
tawazi/config.py

This PR includes suggestions of improvements on documentation level
- [ x ] This change includes a documentation update

doc: enhance home page

---

tawazi/_dag/helpers.py
tawazi/node/node.py

faster logging because of f string suppression

chg: :zap: faster logging

---

tawazi/node/node.py
tests/test_same_op_reuse.py

Fixes an error in the counting of ExecNodes occurences

fix: :bug: fix counting nodes during dag description

---

pyproject.toml
tawazi/_helpers.py
tawazi/errors.py
tests/test_process_passing.py

Include tests to prove that DAG can be run inside a process using pathos or multiprocessing_on_dill

Process passing

---

CHANGELOG.md
pyproject.toml
tawazi/__init__.py

chg: :bookmark: preparing v0.3.2

---

.github/CODEOWNERS

Include CODEOWNERS file 
we are obliged to specify each member because this project is public

new: :sparkles: automatically add reviewers

---

.github/workflows/testing-workflow.yml
README.md

Include Python3.12 in the tests

new: :sparkles: support python3.12

---

tawazi/node/node.py

compaction of operations support 

chg: :recycle: compress operations implementation

---

tawazi/_dag/dag.py
tawazi/_dag/digraph.py
tawazi/_dag/helpers.py
tests/test_build.py
tests/test_cache_feature.py
tests/test_dagexecutor.py
tests/test_profiling.py
tests/test_subgraph.py

Massive overhaul of the tests of DagExecution, as well as overall sanitization of DagExecution abstraction.

Refacto dag execution

---

tests/test_active.py
tests/test_behavior.py
tests/test_build.py
tests/test_compound_priority.py

A small PR to refacto some tests, there will be another PR soon with other tests refactored

chg: :recycle: :white_check_mark: refactor tests with parametrize

---

tawazi/_dag/dag.py
tawazi/_dag/helpers.py
tawazi/_decorators.py
tawazi/node/node.py
tests/test_edge_cases_dag.py
tests/test_same_op_reuse.py
tests/test_subgraph.py
tests/test_typing.py

make DAG as a dataclass. Refacto node_dict => exec_nodes

Refacto dag dataclass

---

documentation/index.md
tawazi/_dag/dag.py
tawazi/_dag/helpers.py
tawazi/_decorators.py
tawazi/_helpers.py
tawazi/consts.py
tawazi/errors.py
tawazi/node/functions.py
tawazi/node/node.py
tawazi/node/uxn.py
tests/test_build.py
tests/test_cache_feature.py
tests/test_dag_compose.py
tests/test_dag_config.py
tests/test_edge_cases_dag.py
tests/test_priority_sequential.py
tests/test_profiling.py
tests/test_subgraph.py

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

chg: :recycle: make ExecNode immutable by extracting ExecNode.result

---

tests/test_exclude_nodes.py
tests/test_exec_nodes.py
tests/test_priority_sequential.py
tests/test_subgraph.py

This PR continues the effort of completely refactoring the tests to make sure they are more useable, cover more test cases, and that it's possible to iterate on them later on.

chg: :recycle: :white_check_mark: refacto more tests

---

tawazi/node/helpers.py
tests/test_future_typing.py

forward porting https://github.com/mindee/tawazi/pull/210

fix: :bug: :green_heart: tuple typing check

---

CHANGELOG.md
pyproject.toml

Tag v0.3.4

---

.github/workflows/formatting-workflow.yml
.github/workflows/testing-workflow.yml
CHANGELOG.md
pyproject.toml
tests/test_xn_alone.py

chg: :twisted_rightwards_arrows: main into v3/main

---

tawazi/node/node.py

chg: :zap: optimize ArgExecNode by using main-thread for assignement

---

CHANGELOG.md
pyproject.toml
tawazi/__init__.py
tawazi/_dag/dag.py
tawazi/node/node.py

This Change is necessary for the latest profiling feature we will use internally.

Fix node construction

---

CHANGELOG.md
pyproject.toml
tawazi/__init__.py
tawazi/_helpers.py
tawazi/errors.py
tawazi/node/node.py
tests/test_dag_input_output.py
tests/test_debug_nodes.py
tests/test_error_location.py
tests/test_setup_nodes.py

Fix problems caused by inheriting from BaseException instead of Exception

Fix exception

---

.github/workflows/testing-workflow.yml
CHANGELOG.md
README.md
pyproject.toml
tawazi/__init__.py
tawazi/config.py

Make tawazi compatible with pydantic v1 and v2 temporarily to make the passage smoother for Tawazi's users

Pydantic v2

---

CHANGELOG.md
tawazi/__init__.py
tests/test_unpack_legacy_typing.py

1. Change the name of a test file
2. do release

chg: :bookmark: preparing v0.6.0
